const COUNTRIES_DATA = [
    {
        code: 'US',
        name: 'United States',
        flag: '🇺🇸',
        capital: 'Washington, D.C.',
        region: 'North America',
        population: 338289857,
        area: 9833520,
        populationDensity: 34,
        birthRate: 11.0,
        deathRate: 8.5,
        gdp: 27360000000000,
        gdpPerCapita: 80937,
        currency: 'USD',
        unemploymentRate: 3.9,
        language: 'English',
        ranking: 1,
        importance: 'The world\'s largest economy and military superpower. Dominates global finance, technology, and culture. Home to Silicon Valley and Wall Street. Key player in international relations and trade.'
    },
    {
        code: 'CN',
        name: 'China',
        flag: '🇨🇳',
        capital: 'Beijing',
        region: 'East Asia',
        population: 1425775850,
        area: 9596961,
        populationDensity: 148,
        birthRate: 7.1,
        deathRate: 7.9,
        gdp: 17890000000000,
        gdpPerCapita: 12556,
        currency: 'CNY',
        unemploymentRate: 5.2,
        language: 'Mandarin Chinese',
        ranking: 2,
        importance: 'Second-largest economy and most populous country. Manufacturing hub of the world. Major investor in infrastructure and technology. Critical to global supply chains and emerging markets.'
    },
    {
        code: 'JP',
        name: 'Japan',
        flag: '🇯🇵',
        capital: 'Tokyo',
        region: 'East Asia',
        population: 123294513,
        area: 377975,
        populationDensity: 326,
        birthRate: 6.3,
        deathRate: 11.8,
        gdp: 4230000000000,
        gdpPerCapita: 34340,
        currency: 'JPY',
        unemploymentRate: 2.4,
        language: 'Japanese',
        ranking: 3,
        importance: 'Advanced economy known for technology and innovation. Leader in robotics, automotive, and electronics. Major financial center. Stable democracy in Asia-Pacific region.'
    },
    {
        code: 'DE',
        name: 'Germany',
        flag: '🇩🇪',
        capital: 'Berlin',
        region: 'Europe',
        population: 83369843,
        area: 357022,
        populationDensity: 233,
        birthRate: 8.6,
        deathRate: 12.3,
        gdp: 4080000000000,
        gdpPerCapita: 48945,
        currency: 'EUR',
        unemploymentRate: 3.0,
        language: 'German',
        ranking: 4,
        importance: 'Europe\'s largest economy and industrial powerhouse. Strong manufacturing sector and automotive industry. Leader in renewable energy. Central to EU integration and policies.'
    },
    {
        code: 'GB',
        name: 'United Kingdom',
        flag: '🇬🇧',
        capital: 'London',
        region: 'Europe',
        population: 67736802,
        area: 242495,
        populationDensity: 279,
        birthRate: 10.7,
        deathRate: 10.3,
        gdp: 3330000000000,
        gdpPerCapita: 49180,
        currency: 'GBP',
        unemploymentRate: 4.1,
        language: 'English',
        ranking: 5,
        importance: 'Leading financial center with London Stock Exchange. Major cultural and political influence. Historic imperial power with significant global networks. G7 member.'
    },
    {
        code: 'FR',
        name: 'France',
        flag: '🇫🇷',
        capital: 'Paris',
        region: 'Europe',
        population: 68017430,
        area: 643801,
        populationDensity: 106,
        birthRate: 10.5,
        deathRate: 9.4,
        gdp: 2930000000000,
        gdpPerCapita: 43114,
        currency: 'EUR',
        unemploymentRate: 7.2,
        language: 'French',
        ranking: 6,
        importance: 'Major cultural and artistic hub. Strong luxury and fashion industries. EU co-founder. Nuclear power leader. Permanent UN Security Council member.'
    },
    {
        code: 'IN',
        name: 'India',
        flag: '🇮🇳',
        capital: 'New Delhi',
        region: 'South Asia',
        population: 1417173173,
        area: 3287263,
        populationDensity: 431,
        birthRate: 16.5,
        deathRate: 7.2,
        gdp: 3736000000000,
        gdpPerCapita: 2389,
        currency: 'INR',
        unemploymentRate: 7.9,
        language: 'Hindi, English',
        ranking: 7,
        importance: 'World\'s most populous country. Fastest-growing major economy. IT industry leader. Large consumer market. Emerging superpower with global influence expanding rapidly.'
    },
    {
        code: 'BR',
        name: 'Brazil',
        flag: '🇧🇷',
        capital: 'Brasília',
        region: 'South America',
        population: 215313498,
        area: 8514877,
        populationDensity: 25,
        birthRate: 12.9,
        deathRate: 7.8,
        gdp: 2117000000000,
        gdpPerCapita: 9202,
        currency: 'BRL',
        unemploymentRate: 8.1,
        language: 'Portuguese',
        ranking: 8,
        importance: 'Latin America\'s largest economy. Rich natural resources including Amazon rainforest. Major agriculture and mining producer. Emerging market with vast potential.'
    },
    {
        code: 'IT',
        name: 'Italy',
        flag: '🇮🇹',
        capital: 'Rome',
        region: 'Europe',
        population: 58940668,
        area: 301340,
        populationDensity: 195,
        birthRate: 7.1,
        deathRate: 11.4,
        gdp: 2010000000000,
        gdpPerCapita: 34088,
        currency: 'EUR',
        unemploymentRate: 7.9,
        language: 'Italian',
        ranking: 9,
        importance: 'Major cultural heritage and tourism destination. Fashion and design capital. Historical influence on Western civilization. G7 member and EU key player.'
    },
    {
        code: 'CA',
        name: 'Canada',
        flag: '🇨🇦',
        capital: 'Ottawa',
        region: 'North America',
        population: 39742830,
        area: 9984670,
        populationDensity: 4,
        birthRate: 10.0,
        deathRate: 8.9,
        gdp: 2138000000000,
        gdpPerCapita: 53715,
        currency: 'CAD',
        unemploymentRate: 5.8,
        language: 'English, French',
        ranking: 10,
        importance: 'Advanced developed nation with abundant natural resources. Major energy producer. Close ally of the US. Multicultural society and stable democracy.'
    },
    {
        code: 'RU',
        name: 'Russia',
        flag: '🇷🇺',
        capital: 'Moscow',
        region: 'Eastern Europe/Asia',
        population: 144656636,
        area: 17098246,
        populationDensity: 8,
        birthRate: 10.4,
        deathRate: 13.1,
        gdp: 2240000000000,
        gdpPerCapita: 15510,
        currency: 'RUB',
        unemploymentRate: 3.2,
        language: 'Russian',
        ranking: 11,
        importance: 'Nuclear superpower with veto power in UN Security Council. Major energy exporter (oil and gas). Geopolitical player in Eastern Europe and Asia. Cultural significance.'
    },
    {
        code: 'KR',
        name: 'South Korea',
        flag: '🇰🇷',
        capital: 'Seoul',
        region: 'East Asia',
        population: 52780961,
        area: 100363,
        populationDensity: 526,
        birthRate: 5.1,
        deathRate: 6.3,
        gdp: 1659000000000,
        gdpPerCapita: 31407,
        currency: 'KRW',
        unemploymentRate: 2.8,
        language: 'Korean',
        ranking: 12,
        importance: 'Technology and electronics leader (Samsung, LG). K-pop and entertainment global influence. Advanced economy with high innovation. Key player in Asian geopolitics.'
    },
    {
        code: 'MX',
        name: 'Mexico',
        flag: '🇲🇽',
        capital: 'Mexico City',
        region: 'North America',
        population: 128932753,
        area: 1964375,
        populationDensity: 66,
        birthRate: 14.2,
        deathRate: 5.9,
        gdp: 1290000000000,
        gdpPerCapita: 10046,
        currency: 'MXN',
        unemploymentRate: 2.6,
        language: 'Spanish',
        ranking: 13,
        importance: 'Latin America\'s second-largest economy. Major trading partner with the US. Growing manufacturing hub. Rich cultural heritage and tourism destination.'
    },
    {
        code: 'ES',
        name: 'Spain',
        flag: '🇪🇸',
        capital: 'Madrid',
        region: 'Europe',
        population: 48080134,
        area: 505990,
        populationDensity: 95,
        birthRate: 7.8,
        deathRate: 9.9,
        gdp: 1392000000000,
        gdpPerCapita: 28963,
        currency: 'EUR',
        unemploymentRate: 12.6,
        language: 'Spanish',
        ranking: 14,
        importance: 'Significant tourist destination and cultural hub. EU member with influence. Recovery from economic crisis shows resilience. Important Mediterranean power.'
    },
    {
        code: 'AU',
        name: 'Australia',
        flag: '🇦🇺',
        capital: 'Canberra',
        region: 'Oceania',
        population: 26068792,
        area: 7692024,
        populationDensity: 3,
        birthRate: 12.0,
        deathRate: 7.4,
        gdp: 1688000000000,
        gdpPerCapita: 64769,
        currency: 'AUD',
        unemploymentRate: 4.0,
        language: 'English',
        ranking: 15,
        importance: 'Developed economy with abundant natural resources. Major mining producer. Key ally in Asia-Pacific region. Important for regional stability and trade.'
    },
    {
        code: 'NL',
        name: 'Netherlands',
        flag: '🇳🇱',
        capital: 'Amsterdam',
        region: 'Europe',
        population: 17530900,
        area: 41543,
        populationDensity: 422,
        birthRate: 9.9,
        deathRate: 9.0,
        gdp: 1098000000000,
        gdpPerCapita: 62619,
        currency: 'EUR',
        unemploymentRate: 3.5,
        language: 'Dutch',
        ranking: 16,
        importance: 'Major trading hub and transportation center. Port of Rotterdam is world\'s busiest. Advanced economy with high quality of life. EU influencer.'
    },
    {
        code: 'CH',
        name: 'Switzerland',
        flag: '🇨🇭',
        capital: 'Bern',
        region: 'Europe',
        population: 8776000,
        area: 41285,
        populationDensity: 212,
        birthRate: 10.4,
        deathRate: 8.4,
        gdp: 924000000000,
        gdpPerCapita: 105313,
        currency: 'CHF',
        unemploymentRate: 2.2,
        language: 'German, French, Italian, Romansh',
        ranking: 17,
        importance: 'Banking and financial services hub. Neutral country with diplomatic importance. High quality of life and innovation leader. Home to major international organizations.'
    },
    {
        code: 'SE',
        name: 'Sweden',
        flag: '🇸🇪',
        capital: 'Stockholm',
        region: 'Europe',
        population: 10497904,
        area: 450295,
        populationDensity: 23,
        birthRate: 10.6,
        deathRate: 8.8,
        gdp: 615000000000,
        gdpPerCapita: 58623,
        currency: 'SEK',
        unemploymentRate: 7.8,
        language: 'Swedish',
        ranking: 18,
        importance: 'Nordic model leader and welfare state example. Tech innovation hub (Spotify, IKEA). High quality of life. EU member and NATO applicant.'
    },
    {
        code: 'TR',
        name: 'Turkey',
        flag: '🇹🇷',
        capital: 'Ankara',
        region: 'Middle East/Europe',
        population: 85326000,
        area: 783562,
        populationDensity: 109,
        birthRate: 15.8,
        deathRate: 6.4,
        gdp: 1078000000000,
        gdpPerCapita: 12632,
        currency: 'TRY',
        unemploymentRate: 8.8,
        language: 'Turkish',
        ranking: 19,
        importance: 'Bridge between Europe and Asia. NATO member with strategic Bosphorus location. Growing economy and regional influence. Cultural crossroads.'
    },
    {
        code: 'SA',
        name: 'Saudi Arabia',
        flag: '🇸🇦',
        capital: 'Riyadh',
        region: 'Middle East',
        population: 36408820,
        area: 2149690,
        populationDensity: 17,
        birthRate: 15.9,
        deathRate: 3.2,
        gdp: 1159000000000,
        gdpPerCapita: 31813,
        currency: 'SAR',
        unemploymentRate: 5.6,
        language: 'Arabic',
        ranking: 20,
        importance: 'World\'s largest oil exporter. OPEC leader and regional powerhouse. Strategic importance in Middle East. Major investor in technology and infrastructure.'
    }
];